Admin settings
FoodIsLifeBGP/banana-rails pull request #111
Opened 2020-09-23 21:49 UTC by trdtnguyen

# Pull Request Template

#### Please check if the PR fulfills these requirements

- [x ] The changes don't come from your master branch. ([Source](https://blog.jasonmeridth.com/posts/do-not-issue-pull-requests-from-your-master-branch/)) 

---

### [Trello Card](https://trello.com/b/vi6WuHYk/admin-portal)
Trello card: "Setting Pages backend support"
#### What kind of change does this PR introduce? 
Implement the Admin Setting page in back-end.
(1) Add the corresponding APIs in `config/routes.rb`.
(2) Add admin controller `app/controllers/admins_controller.rb` to handle the APIs.
(3) Modify the admin model `app/models/admin.rb` to validate input data for admin

Front-end could save settings in the Admin page using `admins/:id/update` API.
#### What is the current behavior? (You can also link to an open issue here)

#### What is the new behavior? (if this is a feature change)

#### Does this PR introduce a breaking change? (What changes might users need to make in their application due to this PR?)
Note that this PR also add API for creating admin. So back-end dev who are working with admins table should carefully check this to avoid duplicate code.

#### Other information

#### Discussion Questions

#### Images (before/ after screenshots, interaction GIFs, ...)

---

#### TODO
 - Handle profile picture
- Corresponding front-end testing is needed.

2020-09-24 15:09 UTC, sagehen03 requested changes
Hey Dat,
This is looking good so far--nice job!  You can add tests in `admins_controller_test.rb` and you can see examples of existing controller tests in `clients_controller_test.rb` `donations_controller.test.rb` you can run the tests from the command line using `rails test`

2020-09-24 15:09 UTC, sagehen03 commented on app/controllers/admins_controller.rb
> +			if @admin.save
I don't think you need to call save here.  `@admin = Admin.create(admin_params)` implies saving to the database if `@admin.valid?` at least that's my understanding.

2020-09-24 15:09 UTC, sagehen03 commented on config/routes.rb
> +  patch 'admins/create', to: 'admins#create'
Since we're creating a new record I think this should be a post rather than patch which is for updates.

2020-09-30 17:28 UTC, trdtnguyen commented on app/controllers/admins_controller.rb
> +			if @admin.save
Agree. I'll remove it in the next PR.

2020-09-30 17:28 UTC, trdtnguyen commented on config/routes.rb
> +  patch 'admins/create', to: 'admins#create'
I'll modify that in the next PR.

2022-10-29 19:03 UTC, closed without merging